### ISSUE TITLE
Can't install tls certificates

### ISSUE THREAD

**Issue by momaek** [stickmy/proxyman#2]
Click TLS Button nothing happened.

Version: v0.2.1
OS Version: macOS 14.4.1

https://github.com/user-attachments/assets/c062da73-9a20-40be-bbca-1f47b99484bb

Log in `proxyman.log`: 
```
06:54:35 [INFO] security verify-cert output: 
```

**Comment by stickmy** [comment]
Fixed in [v0.2.2](https://github.com/stickmy/proxyman/releases/tag/v0.2.2)
